apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovioro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovioro
  template:
    metadata:
      labels:
        app: ovioro
    spec:
      containers:
      - image: okteto.dev/ovioro:latest
        name: ovioro
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/KayDen-html.zip"
        - name: Vless_UUID
          value: "badd8421-63a2-4fb6-825c-9abe6d2e0389"
        - name: Vless_Path
          value: "/badd8421-63a2-4fb6-825c-9abe6d2e0389-vless"
        - name: Vmess_UUID
          value: "badd8421-63a2-4fb6-825c-9abe6d2e0389"
        - name: Vmess_Path
          value: "/badd8421-63a2-4fb6-825c-9abe6d2e0389-vmess"
        - name: Share_Path
          value: "/vrw3ternk"
